name: "Publish hugo site to GitHub Pages"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Set env vars"
        run: |
          export_ga() {
            for _name in "${@}"
            do
              local _key="${_name%%=*}"
              local _value="${_name#*=}"
              [ "${_key}" == "${_name}" ] && _value="${!_name}"
              export $_key="${_value}"
              echo "${_key}=\"${_value}\"" >> "${GITHUB_ENV}"
            done
          }

          export_ga GITHUB_SHA_SHORT="$(git rev-parse --short HEAD)"
          echo "gitrev = '${GITHUB_SHA_SHORT}'" >> src/hugo.toml

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.145.0'

      - name: Build
        run: cd src && hugo --minify

      - name: "Deploy to GitHub Pages"
        if: "success()"
        uses: "crazy-max/ghaction-github-pages@v4.1.0"
        with:
          target_branch: "gh-pages"
          build_dir: "src/public"
          commit_message: "Synchronize website to ${{ env.GITHUB_SHA_SHORT }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"